# Assignment

Import numpy as np

In [2]:

import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
a=[1,2,3,4,5]
a_np=np.array(a)
print(a_np)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [5]:
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
matrix1=np.array(matrix1)
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [7]:
arr=np.arange(1,18,2)
arr.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [9]:
randarr=np.random.randint(0,10,10)
print(randarr)

[5 8 2 9 0 1 6 1 9 9]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [12]:
arr=[1,2,3,4,5]
arr=np.array(arr)
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [14]:
print(arr.shape)

(5,)


Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [31]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2],arr[3],arr[8])

3 4 9


Print alternate elements of that array

In [32]:
print(arr[::2])

[1 3 5 7 9]


Change last 3 elements into 100 using broadcasting and print

In [33]:
print(arr)
arr[7:]=100
arr

[ 1  2  3  4  5  6  7  8  9 10]


array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [34]:
arr1=np.arange(0,25).reshape(5,5)
print(arr1)
print("\nReshaped array:\n")
print(arr1[1:4,1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Reshaped array:

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
